### ISSUE TITLE
sutrauka.py lūžta su 2.5.5 pitonu

### ISSUE THREAD

**Issue by rimas-kudelis** [ispell-lt/ispell-lt#20]
Original Launchpad bug 595257: https://bugs.launchpad.net/ispell-lt/+bug/595257
Reported by: rq (Rimas Kudelis).

rq@sugar:~/src/ispell-lt$ make dist-xpi
cat lietuviu.zodziai lietuviu.jargon lietuviu.vardai lietuviu.veiksmazodziai lietuviu.ivpk lietuviu.ivairus | tools/sutrauka.py > lietuviu.dict

``` tools/sutrauka.py ````````````````````````````````````--
Reading ............................
Processing .............Traceback (most recent call last):
  File "tools/sutrauka.py", line 290, in <module>
    sutrauka(fileinput.input(), myspell=False)
  File "tools/sutrauka.py", line 237, in sutrauka
    '-' * 60 + '\n')
AttributeError: 'str' object has no attribute 'format'
make: *** [lietuviu.dict] Error 1
rq@sugar:~/src/ispell-lt$ python --version
Python 2.5.5

**Comment by rimas-kudelis** [comment]
[ LP comment 1 by: Rimas Kudelis, on 2010-06-16 20:48:03.746188+00:00 ]

su Python 2.6 veikia.

**Comment by rimas-kudelis** [comment]
[ LP comment 2 by: Laimonas Vėbra, on 2010-06-16 20:52:28+00:00 ]

Rimas Kudelis rašė:

> rq@sugar:~/src/ispell-lt$ make dist-xpi
> cat lietuviu.zodziai lietuviu.jargon lietuviu.vardai lietuviu.veiksmazodziai lietuviu.ivpk lietuviu.ivairus | tools/sutrauka.py>  lietuviu.dict
>
> ``` tools/sutrauka.py ````````````````````````````````````--
> Reading ............................
> Processing .............Traceback (most recent call last):
>    File "tools/sutrauka.py", line 290, in<module>
>      sutrauka(fileinput.input(), myspell=False)
>    File "tools/sutrauka.py", line 237, in sutrauka
>      '-' * 60 + '\n')

Taip, čia aš kiek persistengiau (pridirbau); str.format tik nuo v2.6. 
Pataisysiu.
Kol kas gali tas dvi eilutes su .format tiesiog užkomentuoti (jos tik 
statistikai)

**Comment by rimas-kudelis** [comment]
[ LP comment 3 by: Laimonas Vėbra, on 2010-09-21 20:48:37.154580+00:00 ]

Pataisyta 90 revizijoje.
